#localstorage - mongo-pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessModes: 
    - ReadWriteOnce 
  resources:
    requests: 
      storage: 7Gi
      
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-west-2c
    - us-west-2a
    - us-west-2b



