apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
spec:
  ports:
  - name: http
    port: 80
  selector: 
    app: web-app
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  ports:
  - name: http
    port: 8161
  - name: endpoint 
    port: 61616
  selector: 
    app: queue
  type:  ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
      app: position-tracker
  ports:
  - name: http
    port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
      app: api-gateway
  ports:
  - name: http
    port: 8080
  type: ClusterIP
